### ISSUE TITLE
warn parameter of *shell* is not compatible with latest Ansible version

### ISSUE THREAD

**Issue by jeffprestes** [LACNetNetworks/besu-networks#51]
Target Machine: "msg": [
        "Ansible Distribution: Ubuntu",
        "Ansible Dist version: 22.04",
        "Ansible Dist version: 22",
        ""
    ]

Sender machine: ansible-playbook version: [core 2.14.1]

Error: 
TASK [lacchain-writer-node : previous clearing] ****************
fatal: [xxx.xxx.xxx.xxx]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (ansible.legacy.command) module: warn. Supported parameters include: argv, stdin, chdir, _uses_shell, stdin_add_newline, _raw_params, executable, removes, creates, strip_empty_ends."}

Line:
- name: previous clearing
  shell: rm -rf /tmp/besu && mkdir /tmp/besu
  args:
    warn: false

**Comment by jeffprestes** [comment]
As workaround I had removed all 

```
args:
warn: false
```

from the task

**Comment by ccamaleon5** [comment]
https://github.com/LACNetNetworks/besu-networks/pull/59 solved this problem
